# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sy-form-builder"
client_id = "60e96bb74dcbffb3ddff41f35f293392"
application_url = "https://rage-exclusion-burn-survive.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://rage-exclusion-burn-survive.trycloudflare.com/auth/callback",
  "https://rage-exclusion-burn-survive.trycloudflare.com/auth/shopify/callback",
  "https://rage-exclusion-burn-survive.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sachin-rathor.myshopify.com"
